---
# Allow compute credits usage for collaborators and anything pushed to the
# main, staging, and trying branches. (So bors can use them.)
use_compute_credits: |
  $CIRRUS_USER_COLLABORATOR == 'true' ||
  $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH ||
  $CIRRUS_BRANCH =~ 'staging|trying'


# TODO: Convert ruff's output to GitHub annotations
ruff_task: &task
  name: Lint the Python source
  container:
    image: nixpkgs/nix-flakes
  script: nix run $FLAKE_APP
  env:
    FLAKE_APP: .#lint

nixlint_task:
  name: Lint the Nix code
  only_if: changesInclude('.cirrus.yml', 'flake.lock', '**/*.nix')
  <<: *task
  env:
    FLAKE_APP: .#deadnix
  always:
    artifacts:
      path: "*.json"
      type: text/json
      format: cirrus
