[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "memtree"
version = "0.1.0"
description = "Render cgroups tree annotated by memory usage"
authors = ["nicoo <nicoo@debian.org>"]
license = "ISC"

[tool.poetry.scripts]
memtree = 'memtree.cli:main'

[tool.poetry.dependencies]
python = "^3.9"
rich = "^13"


[tool.poetry.group.dev.dependencies]
bork = "^7"

[tool.poetry.group.lint.dependencies]
ruff = "^0.1.3"

[tool.poetry.group.test.dependencies]
pytest = "^7"
hypothesis = "^6.13.5"


[tool.bork.aliases]
lint = "ruff check ."
test = "python -m pytest -v"

[tool.ruff]
select = [
       "E", "W", "F", "C90", # equivalent to flake8 (pycodestyle, pyflakes, mccabe)
       "B", "B9",            # bugbear
       "COM",                # commas
       "I",                  # import order
       "N",                  # naming
]
ignore = [ "E401" ]
line-length = 80

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
