[tool.poetry]
name = "memtree"
version = "0.1.0"
description = ""
authors = ["nicoo <nicoo@debian.org>"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
