[tool.poetry]
name = "memtree"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.2.2"

[tool.poetry.dev-dependencies]
ipython = "^7.23.1"
jupyter = "^1.0.0"
setuptools = "^56.2.0"
wheel = "^0.36.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
