[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "memtree"
version = "0.1.0"
description = ""
authors = ["nicoo <nicoo@debian.org>"]

[tool.poetry.dependencies]
python = "^3.9"
psutil = "^5.8.0"
rich = "^10.2.2"

[tool.poetry.scripts]
memtree = 'memtree.cli:main'


[tool.poetry.dev-dependencies]
bork = "^5.1.0"
flake8 = "^3.9.2"
flake8-import-order = "^0.18.1"
flake8-commas = "^2.0.0"
flake8-bugbear = "^21.4.3"
pep8-naming = "^0.11.1"
pytest = "^6.2.4"
hypothesis = "^6.13.5"

[tool.bork.aliases]
lint = "python -m flake8"
test = "python -m pytest -v"
